-- Generated by nwg-displays on 2026-08-04 at 10:02:14. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "2621x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "1440x900@74.98",
    position = "4541x180",
    scale = 1.0
})
